import type { Metadata } from "next";
import './globals.css';
import {Montserrat, Oxanium} from 'next/font/google'
import logo from "@/assets/logo.svg"


export const metadata: Metadata = {
  title: "DevStage",
  description: "Generated by create next app",
  icons: {
    icon: logo.src
  },
};

const oxanium = Oxanium({
  weight: ['500', '600'],
  subsets: ['latin'],
  variable:'--font-oxanium',
})

const montserrat = Montserrat({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable:'--font-montserrat',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="bg-gray-900 text-gray-100 antialiased bg-[url(/background.png)] bg-no-repeat bg-top md:bg-right-top">
      <main className="max-w-[1200px] mx-auto px-5 py-8 md:py-0">
      {children}
      </main>
      </body>
    </html>
  );
}
